alter table public.categories
  add column if not exists id integer generated by default as identity;

alter table public.categories
  add column if not exists name character varying(120);

update public.categories
set name = concat('Categoria ', id)
where name is null or btrim(name) = '';

alter table public.categories
  alter column name set not null;

alter table public.categories
  add column if not exists description text;

update public.categories
set description = ''
where description is null;

alter table public.categories
  alter column description set default '',
  alter column description set not null;

alter table public.categories
  add column if not exists created_at timestamp with time zone;

update public.categories
set created_at = now()
where created_at is null;

alter table public.categories
  alter column created_at set default now(),
  alter column created_at set not null;

alter table public.categories
  add column if not exists created_by integer;

update public.categories
set created_by = 10447
where created_by is null;

alter table public.categories
  alter column created_by set default 10447,
  alter column created_by set not null;

alter table public.categories
  add column if not exists updated_at timestamp with time zone;

update public.categories
set updated_at = now()
where updated_at is null;

alter table public.categories
  alter column updated_at set default now(),
  alter column updated_at set not null;

alter table public.categories
  add column if not exists updated_by integer;

update public.categories
set updated_by = 10447
where updated_by is null;

alter table public.categories
  alter column updated_by set default 10447,
  alter column updated_by set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.categories'::regclass
      and contype = 'p'
  ) then
    alter table public.categories
      add constraint pk_categories primary key (id);
  end if;
end $$;

create unique index if not exists ix_categories_name
  on public.categories using btree (name)
  tablespace pg_default;

grant select, insert, update, delete on public.categories to authenticated;
grant select on public.categories to anon;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'articles'
      and column_name = 'category_id'
  ) and not exists (
    select 1
    from pg_constraint
    where conname = 'fk_articles_categories_category_id'
  ) then
    alter table public.articles
      add constraint fk_articles_categories_category_id
      foreign key (category_id)
      references public.categories(id)
      on update cascade
      on delete set null
      not valid;
  end if;
end $$;
