create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name character varying(160) not null,
  email character varying(180) not null,
  phone character varying(60) not null default '',
  message text not null,
  status character varying(20) not null default 'unread',
  email_confirmation_sent boolean not null default false,
  email_notification_sent boolean not null default false,
  email_delivery_error text,
  created_at timestamp with time zone not null default now(),
  read_at timestamp with time zone,
  constraint contact_messages_status_check check (status in ('unread', 'read', 'archived'))
);

create index if not exists ix_contact_messages_created_at
  on public.contact_messages (created_at desc);

create index if not exists ix_contact_messages_status
  on public.contact_messages (status);

alter table public.contact_messages enable row level security;
