create table if not exists public.categories (
  id integer generated by default as identity not null,
  name character varying(120) not null,
  description text not null default '',
  created_at timestamp with time zone not null,
  created_by integer not null,
  updated_at timestamp with time zone not null,
  updated_by integer not null,
  constraint pk_categories primary key (id)
) tablespace pg_default;

create unique index if not exists ix_categories_name
  on public.categories using btree (name)
  tablespace pg_default;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'articles'
      and column_name = 'category_id'
  ) and not exists (
    select 1
    from pg_constraint
    where conname = 'fk_articles_categories_category_id'
  ) then
    alter table public.articles
      add constraint fk_articles_categories_category_id
      foreign key (category_id)
      references public.categories(id)
      on update cascade
      on delete set null
      not valid;
  end if;
end $$;
